### ISSUE TITLE
[bug]: Error on terminus build:project:create

### ISSUE THREAD

**Issue by stevector** [pantheon-systems/decoupled-kit-js#96]
### Describe the bug

Running the `terminus build:project:create` command described [in the documentation](https://github.com/pantheon-systems/decoupled-kit-js/blob/canary/web/docs/Backend%20Starters/Decoupled%20Drupal/creating-new-project.md) results in an error message.

```
  The "--profile" option does not exist.
```

### Reproduction

Use Terminus 3 and install the Build Tools plugin using the documentation:

```
terminus self:plugin:install terminus-build-tools-plugin
```

I think the issue is that this installation mechanism brings in [the most recent tagged release of Build Tools (made in January)](https://github.com/pantheon-systems/terminus-build-tools-plugin/releases/tag/3.0.1) and the profile option was added in [February/March](https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/432).

I think the needed resolution is a new tagged release of Build Tools that is installable when running `terminus self:plugin:install terminus-build-tools-plugin`

### Which packages/starters are effected?

- [X] next-drupal
- [ ] gatsby-wordpress
- [ ] drupal-kit
- [ ] wordpress-kit
- [X] documentation
- [ ] monorepo

### Severity

Blocking all usage of Decoupled Kit

### Additional Information

It's probably possible to work around this issue but installing a dev version of the plugin. I knew how to do that in Terminus 2. My few minutes of attempts in Terminus 3 have failed. I think with how small the resolution needed is, we should just cut a new release of Build Tools rather than documenting a work around that puts customers on a branch instead of a tagged release.

**Comment by stevector** [comment]
cc @backlineint @greg-1-anderson @kporras07

**Comment by kporras07** [comment]
Release created: https://github.com/pantheon-systems/terminus-build-tools-plugin/releases/tag/3.0.2 :)

**Comment by stevector** [comment]
Thanks @kporras07! I'm now getting a different error.

```
> ./scripts/composer/project-tasks
📂 💨  Generating Lando configuration file...


  There are no commands defined in the "lando" namespace.


Script ./scripts/composer/project-tasks handling the project-tasks event returned with error code 1
Script @project-tasks was called via post-create-project-cmd
 [error]  Command `composer create-project --working-dir=/private/var/folders/3g/sq1vlybd0d5gvrh01zy50f9c0000gq/T/local-siteWu1WeD  --repository="{\"url\": \"git@github.com:pantheon-systems/decoupled-drupal-recommended.git\", \"type\": \"vcs\"}" pantheon-systems/decoupled-drupal-recommended back-end-umami-for-next -n --stability dev` failed with exit code 1
```

It looks like the repo assumes the existence of a `terminus lando` command? I don't know where that would come from. Is there a Lando plugin for terminus?

**Comment by stevector** [comment]
I'm getting a failed Behat test on the resulting Drupal repo (both for the initial build and another triggered via a whitespace commit):

```
  @api
  Scenario: Login as a user created during this scenario # features/content.feature:33
    Given users:                                         # Drupal\DrupalExtension\Context\DrupalContext::createUsers()
      | name      | status | mail             |
      | Test user | 1      | test@example.com |
    When I am logged in as "Test user"                   # Drupal\DrupalExtension\Context\DrupalContext::assertLoggedInByName()
    Then I should see the link "Log out"                 # Drupal\DrupalExtension\Context\MinkContext::assertLinkVisible()
      No link to 'Log out' on the page https://dev-***********************.pantheonsite.io/user/11?check_logged_in=1 (Exception)
    │
    ╳  Fatal error: Call to a member function call() on null (Behat\Testwork\Call\Exception\FatalThrowableError)
    │
    └─  @AfterStep # FailAid\Context\FailureContext::gatherStateFactsAfterFailedStep()
```

@backlineint is that expected?

**Comment by backlineint** [comment]
@stevector not expected. Best guess is that this test may need to be updated for the Gin admin theme.

Created https://getpantheon.atlassian.net/browse/DB-2786

**Comment by backlineint** [comment]
This did turn out to be an issue with the tests targeting a specific theme. The main build tools CI templates encountered this as well when Drupal changed to Olivero as the default theme. tbt-ci-templates updated this test to accommodate a variety of themes which also resolves this issue.
